version: 2

build:
    os: "ubuntu-24.04"
    tools:
        python: "3.12"
    jobs:
        post_install:
            - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH python -m pip install -e .

sphinx:
    configuration: docs/conf.py

conda:
    environment: docs/environment_rtd.yml



