version: 2

build:
    os: "ubuntu-24.04"
    tools:
        python: "mambaforge-22.9"

sphinx:
    configuration: docs/conf.py

conda:
    environment: docs/environment_rtd.yml

python:
    version: 3.10
    install:
        - method: pip
          path: .

submodules:
    include: all
