version: 2

build:
    os: "ubuntu-24.04"
    tools:
        python: "mambaforge-22.9"
    jobs:
        post_install:
            - conda activate cellpy
            - python -m pip install -e .

sphinx:
    configuration: docs/conf.py

conda:
    environment: docs/environment_rtd.yml



