name: cellpy_dev
channels:
    - conda-forge
dependencies:
    - python >=3.10
    - PyGithub
    - black
    - bumpver
    - click
    - cookiecutter
    - coverage
    - cryptography
    - dateparser
    - fabric
    - graphviz
    - hdf5
    - invoke
    - ipykernel
    - ipython
    - ipywidgets
    - jupyterlab
    - lmfit
    - matplotlib
    - myst-parser
    - nbmake
    - nbsphinx
    - nox
    - numpy >= 2.0
    - openpyxl
    - pandas
    - pandoc
    - pint
    - pip
    - plotly
    - plotly
    - pyodbc
    - pytables
    - pytest
    - pytest-benchmark
    - pytest-timeout
    - python-box
    - python-dotenv
    - python-dotenv
    - requests
    - rich
    - ruamel.yaml
    - scipy
    - seaborn
    - setuptools
    - sphinx
    - sphinx-autoapi
    - sphinx_rtd_theme
    - sqlalchemy
    - sqlalchemy-access
    - tqdm
    - twine
    - xlrd
    - pip:
        - bump-my-version
        - isort
        - jinja2_time
        - jupyterlab-code-formatter
        - kaleido==0.1.*
        - myst_nb
        - pip-tools
        - pipdeptree
        - pydeps
        - sphinx-book-theme


