name: cellpy_dev
channels:
    - conda-forge
dependencies:
    - python=3.11
    - pip
    - numpy
    - openpyxl
    - xlrd
    - cryptography
    - click
    - scipy
    - pandas
    - setuptools
    - ruamel.yaml
    - pyodbc
    - PyGithub
    - cookiecutter
    - tqdm
    - dateparser
    - hdf5
    - pytables
    - python-box
    - pint
    - sqlalchemy
    - python-dotenv
    - fabric
    - lmfit
    - matplotlib
    - plotly
    - ipython
    - ipywidgets
    - ipykernel
    - rich
    - coverage
    - pytest
    - pytest-timeout
    - pytest-benchmark
    - nox
    - black
    - plotly
    - seaborn
    - sphinx
    - nbsphinx
    - sqlalchemy-access
    - pandoc
    - graphviz
    - sphinx-autoapi
    - invoke
    - twine
    - build
    - bumpver
    - python-dotenv
    - myst-parser
    - sphinx_rtd_theme
    - nbmake
    - pip:
        - pipdeptree
        - pydeps
        - pip-tools
        - myst_nb
        - sphinx-book-theme


