"""Pinned behavior contract for the deliberately-broken fixtures (#655).

The fixtures under ``testdata/bad/`` (generated by ``dev/make_bad_fixtures.py``)
each isolate one defect in the custom-CSV loader path. These tests pin how
cellpy *currently* behaves on each, so a future change that makes cellpy crash
(or silently corrupt) where it used to cope — or vice versa — is caught.

A declared-but-absent column used to be a silent drop (#761). That case now
raises ``LoaderError`` at load time.
"""

from __future__ import annotations

import warnings

import numpy as np
import pytest

from cellpy import cellreader
from cellpy.exceptions import LoaderError

from . import fdv

# native_schema=False keeps the loader's legacy column names on the raw frame.
VOLTAGE = "voltage"
CYCLE_INDEX = "cycle_index"


def _load_bad(path: str) -> cellreader.CellpyCell:
    """Load a bad fixture through the custom loader (legacy parsing contract)."""
    cell = cellreader.CellpyCell(native_schema=False)
    cell.set_instrument(
        instrument="custom", instrument_file=fdv.bad_custom_instrument_path
    )
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        cell.from_raw(path)
    return cell


def test_good_small_loads_cleanly():
    """Sanity anchor: the un-broken small slice loads with no NaN/Inf."""
    c = _load_bad(fdv.bad_good_small_path)
    raw = c.data.raw
    assert len(raw) == 60
    assert sorted(set(raw[CYCLE_INDEX].tolist())) == [1]
    assert int(raw[VOLTAGE].isna().sum()) == 0
    assert not np.isinf(raw[VOLTAGE].to_numpy(dtype=float)).any()


def test_nan_inf_values_are_preserved_not_dropped():
    """cellpy does not filter NaN/Inf at load — the bad values survive in raw.

    Documented behavior, not necessarily desired: downstream consumers must not
    assume the raw frame is finite. If cellpy ever grows load-time filtering,
    update this pin (and the counts).
    """
    c = _load_bad(fdv.bad_nan_inf_path)
    raw = c.data.raw
    v = raw[VOLTAGE].to_numpy(dtype=float)
    assert len(raw) == 60  # no rows dropped
    assert int(np.isnan(v).sum()) == 1
    assert int(np.isinf(v).sum()) == 2


def test_missing_cycle_gap_is_preserved():
    """A non-contiguous cycle index (1, 3) is kept as-is — no fabricated cycle 2.

    This is the graceful behavior we want: cellpy neither invents the missing
    cycle nor renumbers the survivors.
    """
    c = _load_bad(fdv.bad_missing_cycle_path)
    raw = c.data.raw
    cycles = sorted({int(x) for x in raw[CYCLE_INDEX].dropna().tolist()})
    assert cycles == [1, 3]
    assert len(raw) == 40  # the 20-row cycle-2 block is gone, nothing else


def test_truncated_file_is_tolerated():
    """A file cut mid-row loads without crashing (trailing partial row → NaNs)."""
    c = _load_bad(fdv.bad_truncated_path)
    raw = c.data.raw
    assert len(raw) >= 59  # the intact rows survive; partial row parsed w/ NaNs


@pytest.mark.essential
def test_missing_column_raises_loader_error():
    """A declared column absent from the file is a load-time error (#761)."""
    cell = cellreader.CellpyCell(native_schema=False)
    cell.set_instrument(
        instrument="custom", instrument_file=fdv.bad_custom_instrument_path
    )
    with pytest.raises(LoaderError, match="voltage"):
        cell.from_raw(fdv.bad_missing_column_path)
