name: Run pytest on macos (conda)
on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Install-miniconda-and-run-pytest:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          miniconda-version: latest
          activate-environment: cellpy_dev
          environment-file: github_actions_environment.yml
          python-version: ${{ matrix.python-version }}

      - name: Conda info
        run: conda info

      - name: Conda list
        run: conda list

      - name: Install mdbtools
        run: |
          brew install mdbtools
#          sudo apt-get install -y mdbtools

      - name: pytest
        run: pytest

